name: Build app

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip3 install pillow pyinstaller
    - name: Build with Pyinstaller
      run: |
        pyinstaller BetterCovers.py --add-data "/media/*:./media" --add-data "/cover.*:./" --onefile
